name: testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Initialise Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies for Python ${{ matrix.python-version }}
        run: |
          poetry env use "${{ matrix.python-version }}"
          poetry install
      - name: Run Tests
        run: |
          poetry env info
          poetry run pytest